name: Pull Request

on:
  pull_request:
    branches:
      - "develop"
      - "master"
    types: [ opened, reopened, review_requested, ready_for_review ]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
  code-analysis:
    name: Run Detekt for static code analysis
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Detekt
        run: bash ./gradlew --parallel detekt
